version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django1
    ports:
      - 8000:8000

    image: app:django1
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
