
name: Django Tests

 on:
   push:
     -main



pull_request:
  branches:
    - main



 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v2
       - name: Set up Python 3.11
         users: actions/setup-python@v2
         with:
           python-version: 3.11
      - name: install dependecies
        run: |
          python -m pip install --upgraded pip
          pip install -r requirements.txt
      - name:  Lint with flake8
        run: |
          pip install flake8
          flake8
      - name: Coverage report
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report
      -name: Django Testing
       run: |
         python3 manage.py test
